# Generated by Django 2.1.7 on 2019-02-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('pending', 'pending'), ('finished', 'finished'), ('failed', 'failed')], default='pending', max_length=10)),
                ('result', models.IntegerField(null=True)),
                ('comment', models.TextField(null=True)),
            ],
        ),
    ]
